/**
 * constant.js
 */

module.exports = {
  AN_PLUS_B: 'AnPlusB',
  AT_RULE: 'Atrule',
  AT_RULE_PRELUDE: 'AtrulePrelude',
  ATTRIBUTE_SELECTOR: 'AttributeSelector',
  BLOCK: 'Block',
  BRACKETS: 'Brackets',
  CDC: 'CDC',
  CDO: 'CDO',
  CLASS_SELECTOR: 'ClassSelector',
  COMBINATOR: 'Combinator',
  COMMENT: 'Comment',
  DECLARATION: 'Declaration',
  DECLARATION_LIST: 'DeclarationList',
  DIMENSION: 'Dimension',
  FUNCTION: 'Function',
  HASH: 'Hash',
  ID_SELECTOR: 'IdSelector',
  IDENTIFIER: 'Identifier',
  MEDIA_FEATURE: 'MediaFeature',
  MEDIA_QUERY: 'MediaQuery',
  MEDIA_QUERY_LIST: 'MediaQueryList',
  NESTING_SELECTOR: 'NestingSelector',
  N_TH: 'Nth',
  NUMBER: 'Number',
  OPERATOR: 'Operator',
  PARENTHESES: 'Parentheses',
  PERCENTAGE: 'Percentage',
  PSEUDO_CLASS_SELECTOR: 'PseudoClassSelector',
  PSEUDO_ELEMENT_SELECTOR: 'PseudoElementSelector',
  RATIO: 'Ratio',
  RAW: 'Raw',
  RULE: 'Rule',
  SELECTOR: 'Selector',
  SELECTOR_LIST: 'SelectorList',
  STRING: 'String',
  STYLE_SHEET: 'StyleSheet',
  TYPE_SELECTOR: 'TypeSelector',
  UNICODE_RANGE: 'UnicodeRange',
  URL: 'Url',
  VALUE: 'Value',
  WHITESPACE: 'WhiteSpace'
};
