export class Finder {
    constructor(window: object);
    get window(): object;
    get document(): any;
    get root(): any;
    get shadow(): boolean;
    get tracker(): EventTracker;
    get warn(): boolean;
    get astCache(): WeakMap<WeakKey, any>;
    get node(): any;
    get verifyShadowHost(): null;
    onError: (e: Error, opt?: {
        noexcept?: boolean | undefined;
    }) => void;
    setup: (selector: string, node: object, { check, noexcept, warn }?: {
        check?: boolean | undefined;
        noexcept?: boolean | undefined;
        warn?: boolean | undefined;
    }) => object;
    clearResults: (all?: boolean) => void;
    private _processSelectorBranches;
    private _correspond;
    private _createTreeWalker;
    private _getSelectorBranches;
    private _getFilteredChildren;
    private _matchPseudoClassSelector;
    private _evaluateHostPseudo;
    private _evaluateHostContextPseudo;
    private _matchShadowHostPseudoClass;
    private _matchSelectorForElement;
    private _matchSelectorForShadowRoot;
    private _matchSelector;
    private _matchLeaves;
    private _getFilterLeaves;
    private _traverseAllDescendants;
    private _findDescendantNodes;
    private _collectCombinatorMatches;
    private _matchCombinator;
    private _traverseAndCollectNodes;
    private _findPrecede;
    private _findNodeWalker;
    private _matchSelf;
    private _findLineal;
    private _findEntryNodesForPseudoElement;
    private _findEntryNodesForId;
    private _findEntryNodesForClass;
    private _findEntryNodesForType;
    private _findEntryNodesForOther;
    private _findEntryNodes;
    private _determineTraversalStrategy;
    private _processPendingItems;
    private _collectNodes;
    private _getCombinedNodes;
    private _matchNodeNext;
    private _matchNodePrev;
    private _processComplexBranchAll;
    private _processComplexBranchFirst;
    find: (targetType: string) => Set<object>;
    getAST: (selector: string) => object;
    getDocumentURL(): string;
    #private;
}
import { EventTracker } from './event-tracker.js';
