export class Finder {
    constructor(window: object);
    private _onError;
    private _setup;
    private _correspond;
    private _createTreeWalker;
    private _prepareQuerySelectorWalker;
    private _traverse;
    private _collectNthChild;
    private _collectNthOfType;
    private _matchAnPlusB;
    private _matchHasPseudoFunc;
    private _matchLogicalPseudoFunc;
    private _matchPseudoClassSelector;
    private _matchShadowHostPseudoClass;
    private _matchSelector;
    private _matchLeaves;
    private _matchHTMLCollection;
    private _findDescendantNodes;
    private _matchCombinator;
    private _findNode;
    private _matchSelf;
    private _findLineal;
    private _findFirst;
    private _findFromHTMLCollection;
    private _findEntryNodes;
    private _getEntryTwig;
    private _collectNodes;
    private _getCombinedNodes;
    private _matchNodeNext;
    private _matchNodePrev;
    private _matchNodes;
    private _find;
    matches(selector: string, node: object, opt: object): boolean;
    closest(selector: string, node: object, opt: object): object | null;
    querySelector(selector: string, node: object, opt: object): object | null;
    querySelectorAll(selector: string, node: object, opt: object): Array<object | undefined>;
    #private;
}
