export function getType(o: object): string;
export function verifyArray(arr: any[], type: string): any[];
export function generateException(msg: string, name: string, globalObject?: object): DOMException;
export function resolveContent(node: object): Array<object | boolean>;
export function traverseNode(node: object, walker: object, force?: boolean): object | null;
export function isCustomElement(node: object, { formAssociated }?: {
    formAssociated?: boolean | undefined;
}): boolean;
export function getSlottedTextContent(node: object): string | null;
export function getDirectionality(node: object, dirCache?: WeakMap<any, any>): string | null;
export function getLanguageAttribute(node: object, langCache?: WeakMap<any, any>): string | null;
export function isContentEditable(node: object): boolean;
export function isVisible(node: object): boolean;
export function isFocusVisible(node: object): boolean;
export function isFocusableArea(node: object): boolean;
export function isFocusable(node: object): boolean;
export function getNamespaceURI(ns: string, node: object): string | null;
export function isNamespaceDeclared(ns?: string, node?: object): boolean;
export function isPreceding(nodeA: object, nodeB: object): boolean;
export function compareNodes(a: object, b: object): number;
export function sortNodes(nodes?: Array<object> | Set<object>): Array<object>;
export function findBestSeed(nodes: any[], state?: object): object;
export function populateHasAllowlist(current: object, list: WeakSet<any>, visitedAncestors: Set<any>): void;
export function collectAllDescendants(node: Document | DocumentFragment | Element, document: Document): Array<Element>;
