name: benchmark
permissions:
  contents: read

on:
  pull_request:
    branches: [ main ]
  release:
    types: [ created ]

jobs:
  benchmark:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js lts/*
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          check-latest: true
      - run: npm ci
      - run: npm run bench
      - run: npm run bench-sizzle
