name: benchmark

on:
  release:
    types: [ created ]

jobs:
  benchmark:
    strategy:
      matrix:
        node-version: lts/*
        os: [ ubuntu-latest, macos-latest, windows-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm run benchmark
